version = 0.1
[default.deploy.parameters]
stack_name = "bytebox"
resolve_s3 = true
s3_prefix = "bytebox"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPoolAdminGroupName=\"apiAdmins\" CustomerSupportGroupName=\"customerSupport\""
image_repositories = []
